### ISSUE TITLE
downsampling code

### ISSUE THREAD

**Issue by leoscholl** [aolabNeuro/analyze#123]
i'm not clear which methods to use. scipy has `decimate()` and `resample()` methods, which include some filtering. maybe we also want to write our own simpler function similar to the top answer here: https://stackoverflow.com/questions/20322079/downsample-a-1d-numpy-array

**Comment by m-nolan** [comment]
I use [`scipy.signal.decimate`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.decimate.html) when downsampling ECoG data from 1kHz to 250Hz. I'm not sure what the difference between `decimate()` and `resample` are, but I know that decimate only downsamples by a given factor (in my case 4) while resample can either upsample or downsample. Here's [a more detailed breakdown of the two functions](https://dsp.stackexchange.com/questions/45446/pythons-tt-resample-vs-tt-resample-poly-vs-tt-decimate) with a third option, `resample_poly()`.

I'll dig around and see if I can find a clear implementation difference between the two. Both use freq-domain filtering to apply an anti-aliasing filter, but I don't know what kind of filter `resample()`. The documentation for `decimate()` says: "By default, an order 8 Chebyshev type I filter is used. A 30 point FIR filter with Hamming window is used if ftype is ‘fir’." and `resample()` just says that it filters using the "fourier method." 🤷

**Comment by m-nolan** [comment]
Update: It's hard to ferret out exactly, but `sp.signal.decimate` appears to use the standard convolution implementation (i.e. flip and correlate) from numpy. Resample uses an fft-based convolution algorithm, which is in most all cases much faster. I'll run some tests to see if one is faster than the other on some ECoG data.

Both methods should give you similar outcomes. The type-I chebyshev filter used by default in `decimate()` will distort some high-frequency signal components due to the group delay. A type-II would fix this; so would using an FIR filter (which is a parameter input-level option for the function). I'm using `decimate()`, but I might want to reassess this.
